import os

DEFAULT_MAPS = {
    "mp_coop_start",
    "mp_coop_tbeam_polarity3",
    "sp_a3_bomb_flings",
    "sp_a2_trust_fling",
    "mp_coop_mic_calibration",
    "sp_a2_ricochet",
    "sp_a2_laser_chaining",
    "mp_coop_wall_intro",
    "mp_coop_tbeam_maze",
    "mp_coop_paint_speed_catch",
    "sp_a2_bts1",
    "mp_coop_button_tower",
    "sp_a2_laser_over_goo",
    "mp_coop_fan",
    "mp_coop_trap_1",
    "mp_coop_wall_catch",
    "mp_coop_tbeam_laser_1",
    "mp_coop_doors",
    "sp_a2_bridge_intro",
    "sp_a1_wakeup",
    "mp_coop_fling_3",
    "mp_coop_paint_red_racer",
    "sp_a1_intro1",
    "mp_coop_tbeam_catch_grind_1",
    "mp_coop_multifling_1",
    "sp_a2_laser_vs_turret",
    "mp_coop_tbeam_polarity2",
    "e1912",
    "mp_coop_rat_maze",
    "mp_coop_fling_crushers",
    "mp_coop_catapult_2",
    "sp_a2_pull_the_rug",
    "sp_a2_catapult_intro",
    "mp_coop_tbeam_redirect",
    "sp_a1_intro2",
    "mp_coop_infinifling_train",
    "mp_coop_fling_1",
    "mp_coop_paint_redirect",
    "sp_a3_01",
    "mp_coop_paint_bridge",
    "mp_coop_paint_walljumps",
    "sp_a3_03",
    "sp_a4_finale4",
    "mp_coop_race_1",
    "mp_coop_double_catch",
    "sp_a2_column_blocker",
    "mp_coop_race_2",
    "mp_coop_paint_speed_fling",
    "sp_a3_transition01",
    "sp_a3_crazy_box",
    "mp_coop_wall_1",
    "sp_a3_00",
    "mp_coop_credits",
    "sp_a2_laser_stairs",
    "sp_a2_turret_blocker",
    "mp_coop_turret_ball",
    "mp_coop_wall_stop",
    "sp_a4_jump_polarity",
    "sp_a2_dual_lasers",
    "sp_a4_tb_polarity",
    "sp_a4_intro",
    "sp_a4_laser_catapult",
    "mp_coop_turret_walls",
    "mp_coop_wall_block",
    "sp_a4_finale2",
    "sp_a2_bts3",
    "sp_a2_laser_relays",
    "sp_a1_intro6",
    "sp_a2_triple_laser",
    "mp_coop_wall_2",
    "sp_a4_tb_catch",
    "sp_a4_finale3",
    "sp_a2_bts6",
    "mp_coop_catapult_wall_intro",
    "mp_coop_laser_1",
    "sp_a4_tb_wall_button",
    "sp_a2_bts4",
    "mp_coop_wall_6",
    "mp_coop_laser_crusher",
    "mp_coop_laser_bypass",
    "sp_a2_intro",
    "mp_coop_wall_straight_jump",
    "sp_a4_tb_trust_drop",
    "mp_coop_laser_2",
    "sp_a2_laser_intro",
    "mp_coop_lobby_2",
    "sp_a1_intro5",
    "mp_coop_race_3",
    "sp_a5_credits",
    "mp_coop_wall_3",
    "sp_a2_bts5",
    "mp_coop_tbeam_polarity",
    "mp_coop_tbeam_end",
    "mp_coop_laser_3",
    "mp_coop_paint_come_along",
    "mp_coop_come_along",
    "mp_coop_teambts",
    "sp_a2_pit_flings",
    "mp_coop_paint_longjump_intro",
    "sp_a4_speed_tb_catch",
    "mp_coop_catapult_1",
    "sp_a2_turret_intro",
    "sp_a4_laser_platform",
    "sp_a3_speed_ramp",
    "mp_coop_wall_5",
    "sp_a3_end",
    "sp_a1_intro3",
    "sp_a3_jump_intro",
    "mp_coop_vista",
    "sp_a2_bridge_the_gap",
    "mp_coop_laser_redirect",
    "sp_a4_stop_the_box",
    "sp_a2_sphere_peek",
    "sp_a4_tb_intro",
    "sp_a1_intro4",
    "sp_a2_fizzler_intro",
    "mp_coop_tbeam_drill",
    "sp_a3_speed_flings",
    "sp_a1_intro7",
    "sp_a2_core",
    "sp_a3_portal_intro",
    "sp_a2_bts2",
    "sp_a4_finale1",
}

CUSTOM_MAPS = []

def scan_custom_maps(portal_dir_path):
    global CUSTOM_MAPS
    CUSTOM_MAPS = []

    maps_path = os.path.join(portal_dir_path, 'portal2', 'maps')
    if not os.path.exists(maps_path):
        return

    for filename in os.listdir(maps_path):
        if filename.endswith('.bsp'):
            map_name = filename[:-4]
            if map_name not in DEFAULT_MAPS:
                CUSTOM_MAPS.append(map_name)
